Add ja3 signature to handshake session
lafaspot/ja3_4java pull request #3
Opened 2018-11-02 02:03 UTC by ajathan

2018-11-02 18:13 UTC, nvsnvikram commented on src/main/java/com/lafaspot/ja3_4java/JA3SSLEngineWrapper.java
> +		} else {
I haven't fully reviewed this code. The idea is to make the flows to unwrap post handshake fast with as many less checks as possible. The handshake + ja3 generation can be somewhat expensive and still efficient. Can you review the code and see?

2018-11-02 18:15 UTC, nvsnvikram commented
👎 

Can you also add README.md to this project?

2018-11-05 20:48 UTC, nvsnvikram commented on src/main/java/com/lafaspot/ja3_4java/JA3SSLEngineWrapper.java
> +    private boolean isJa3SignatureSet = false;
How is this different from ja3 != null?

2018-11-05 20:49 UTC, nvsnvikram commented on src/main/java/com/lafaspot/ja3_4java/JA3SSLEngineWrapper.java
> +    private boolean isJa3SignatureSet = false;
ok, see it now. This is ja3 completed.

2018-11-05 20:52 UTC, nvsnvikram commented on src/main/java/com/lafaspot/ja3_4java/JA3SSLEngineWrapper.java
> +		final SSLEngineResult result;
Would this work?

    @Override
    public SSLEngineResult unwrap(final ByteBuffer src, final ByteBuffer[] dsts, final int offset, final int length) throws SSLException {
		if (!ja3Done) {
		    if (ja3Signature != null) {
		        final SSLSession handshakeSession = engine.getHandshakeSession();
		        if (handshakeSession != null) {
		            // Set ja3 signature in handshake session
		            handshakeSession.putValue(JA3Constants.JA3_FINGERPRINT, ja3);
		            ja3Done = true;
		        }
		    } else {
		        // 1. Generate JA3 signature
		        final HandshakeStatus handshakeStatus = engine.getHandshakeStatus();
		        if (HandshakeStatus.FINISHED == handshakeStatus) {
				    ja3Done = true;
			    } else {
			        ja3 = new JA3Signature().ja3Signature(src);
			    }
		    }
		}

		return engine.unwrap(src, dsts, offset, length);
    }

2018-11-05 20:54 UTC, nvsnvikram requested changes
Please review my changes and reply back

2018-11-07 02:26 UTC, ajathan commented on src/main/java/com/lafaspot/ja3_4java/JA3SSLEngineWrapper.java
> +		final SSLEngineResult result;
done

2018-11-07 19:37 UTC, nvsnvikram approved these changes

2018-11-07 19:39 UTC, merged